Code Release 2019
Co-authored-by: Maximilian Schmidt <maximilian@schmidt.so>
Co-authored-by: Felix Wege <felix.wege@tuhh.de>
Co-authored-by: Bendodroid <bendodroid@icloud.com>
Co-authored-by: Pascal Gleske <pascalgleske+github@gmail.com>
Co-authored-by: Konrad Nölle <konrad@familie-noelle.de>
Co-authored-by: Pascal Loth <pascal.loth@tuhh.de>
Co-authored-by: Martin Borchert <martin.borchert@tuhh.de>
Co-authored-by: Nicolas Riebesel <nicolas.riebesel@gmx.com>
Co-authored-by: Justus Basler <justus@baslerteam.de>
Co-authored-by: Erik Schröder <schroedererik@mailbox.org>
Co-authored-by: andreeja <andrea.essig@tuhh.de>
Co-authored-by: Darshana Adikari <darshanaads@gmail.com>
Co-authored-by: Lasse Peters <lasse.peters@tuhh.de>
Co-authored-by: Chris Kafendt <c.kahlefendt@gmail.com>
Co-authored-by: Lasse Grefe <lasse.grefe@t-online.de>
Co-authored-by: Yuria Konda <yuria.konda@tuhh.de>
Co-authored-by: Thomas Schattschneider <tschattschneider@mailbox.org>

diff --git a/tools/ctc-hulks/functions b/tools/ctc-hulks/functions
--- a/tools/ctc-hulks/functions
+++ b/tools/ctc-hulks/functions
@@ -24,3 +24,35 @@ function hg_clone
   hg up $VERSION
   cd ..
 }
+
+function download
+{
+  URL=$1
+  OUTPUT_NAME=$2
+
+  if [[ $OUTPUT_NAME == "" ]]; then
+    wget -nc $URL -q --show-progress
+  else
+    wget -nc $URL -O $OUTPUT_NAME -q --show-progress
+  fi
+
+  RETURNCODE=$?
+
+  if [[ $RETURNCODE != 0 ]] && [[ $RETURNCODE != 1 ]]; then
+    echo -e "\033[0;31mDownloading $URL failed!"
+    rm $OUTPUT_NAME
+    exit 1
+  fi
+}
+
+function unpack
+{
+  echo "Unpacking $1"
+
+  tar xkf $1
+
+  if [[ $? != 0 ]]; then
+    echo -e "\033[0;31mUnpacking $1 failed!"
+    exit 1
+  fi
+}
